CREATE TABLE IF NOT EXISTS RAIDBOSS(ID INTEGER PRIMARY KEY AUTOINCREMENT, BOSS TEXT NOT NULL, STRENGTH INT);
CREATE TABLE IF NOT EXISTS NOTIFICATIONS(ID INTEGER PRIMARY KEY AUTOINCREMENT, RAIDID INTEGER NOT NULL, PLAYERID INTEGER NOT NULL, READY BOOLEAN DEFAULT 0);
CREATE TABLE IF NOT EXISTS USERS(ID INT PRIMARY KEY NOT NULL, NAME TEXT NOT NULL, TEAM TEXT NOT NULL, LEVEL SMALLINT NOT NULL, FIRSTNAME TEXT, SURNAME TEXT, USERNAME TEXT, NOTIFICATIONS BOOLEAN DEFAULT 0, HEARTBEAT DATETIME, LANGUAGE INT DEFAULT 1);
CREATE TABLE IF NOT EXISTS RAID(ID INTEGER PRIMARY KEY AUTOINCREMENT, CREATED_BY INT NOT NULL, BOSS TEXT NOT NULL, LAT FLOAT NOT NULL, LONG FLOAT NOT NULL, TIME DATETIME NOT NULL, GYM TEXT, READY BOOLEAN DEFAULT 0);
CREATE TABLE IF NOT EXISTS RAIDPLAYERS(ID INTEGER PRIMARY KEY AUTOINCREMENT, RAIDID INTEGER NOT NULL, PLAYERID INTEGER NOT NULL, FRIENDS INTEGER DEFAULT 0, PREFERRED_TIME DATETIME DEFAULT (datetime('now','localtime')));
CREATE TABLE IF NOT EXISTS LANGUAGES(ID INTEGER PRIMARY KEY AUTOINCREMENT, LANGUAGE TEXT NOT NULL);
INSERT OR IGNORE INTO LANGUAGES (ID,LANGUAGE) VALUES (1,'ENGLISH');
INSERT OR IGNORE INTO LANGUAGES (ID,LANGUAGE) VALUES (2,'ITALIAN');
INSERT OR IGNORE INTO LANGUAGES (ID,LANGUAGE) VALUES (3,'DUTCH');
